name: TMCloud CI

  on:
    push:
      branches: [ main, develop ]
    pull_request:
      branches: [ main ]

  jobs:
    basic-check:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install basic dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask click

      - name: Basic syntax check
        run: |
          python -m py_compile *.py
          echo "✅ Python syntax check passed"

      - name: Test Flask import
        run: |
          python -c "import flask; print('✅ Flask imported successfully')"

      - name: Create test database
        run: |
          python scripts/create_test_database.py
          echo "✅ Test database created"

      - name: Basic database check
        run: |
          python -c "
          import sqlite3
          conn = sqlite3.connect('test_data/test_ci.db')
          cursor = conn.cursor()
          cursor.execute('SELECT COUNT(*) FROM jiken_c_t')
          count = cursor.fetchone()[0]
          print(f'✅ Database contains {count} test records')
          conn.close()
          "
