name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read
  actions:  read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_PATH: test_output.db   # 軽量 DB を使う

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Swap in lightweight test DB
        run: |
          if [ -f test_output.db ]; then cp test_output.db output.db; fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        if: ${{ hashFiles('tests/**') != '' }}
        run: pytest -q

      - name: Sanity check DB
        run: python cli_trademark_search.py --limit 1 || true

      - name: Package application (git archive)
        run: git archive --format=tar.gz --output=tmcloud-staging.tar.gz HEAD

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tmcloud-staging
          path: tmcloud-staging.tar.gz
