name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read
  actions:  read        # ログを Claude が読む用（任意）

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_PATH: test_output.db     # 軽量 DB を使用

    steps:
      # 1) チェックアウト（LFS 有効）
      - uses: actions/checkout@v4
        with:
          lfs: true

      # 2) 軽量 DB に差し替え
      - name: Swap in lightweight test DB
        run: |
          if [ -f test_output.db ]; then cp test_output.db output.db; fi

      # 3) Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      # 4) 依存
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 5) テスト（無ければスキップ）
      - name: Run tests
        if: ${{ hashFiles('tests/**') != '' }}
        run: pytest -q

      # 6) 簡易 DB 動作確認（失敗しても落とさない）
      - name: Sanity check DB
        run: python cli_trademark_search.py --limit 1 || true

      # 7) パッケージ化（Git 管理下のファイルだけ）
      - name: Package application
        run: |
          cd "$GITHUB_WORKSPACE"
          tar --exclude='.git' -czf tmcloud-staging.tar.gz $(git ls-files)

      # 8) アーティファクト
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tmcloud-staging
          path: tmcloud-staging.tar.gz
