name: Claude Code

permissions:
  id-token: write
  contents: read
  issues: write

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, edited]

jobs:
  run-claude:
    runs-on: ubuntu-latest
    permissions:  # 👈 jobレベルにも明記！
      id-token: write
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: anthropics/claude-code-action@v0
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}   # 👈 明示的に渡す！
