name: Claude Code

permissions:
  id-token: write
  contents: read

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, edited]

jobs:
  run-claude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anthropics/claude-code-action@v0
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
