name: Cleanup and Maintenance

on:
  schedule:
    - cron: '0 2 * * 0'        # 毎週日曜 02:00 UTC
  workflow_dispatch:

jobs:
  cleanup-temp-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for old temporary files
        run: |
          if [ -d "scripts/tmp" ]; then
            echo "Checking for files older than 30 days in scripts/tmp/"
            OLD_FILES=$(find scripts/tmp -type f -mtime +30 2>/dev/null || true)

            if [ -n "$OLD_FILES" ]; then
              echo "Found old temporary files:"
              echo "$OLD_FILES"
              echo "OLD_FILES<<EOF" >> $GITHUB_ENV
              echo "$OLD_FILES" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
              echo "CLEANUP_NEEDED=true" >> $GITHUB_ENV
            else
              echo "No old temporary files found"
              echo "CLEANUP_NEEDED=false" >> $GITHUB_ENV
            fi
          else
            echo "scripts/tmp/ directory does not exist"
            echo "CLEANUP_NEEDED=false" >> $GITHUB_ENV
          fi

      - name: Create cleanup issue
        if: env.CLEANUP_NEEDED == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const oldFiles = process.env.OLD_FILES;
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Cleanup Required: Old Temporary Files Found',
              body: `
            ## Temporary Files Cleanup Required

            The following temporary files are older than 30 days and should be reviewed for cleanup:

            \`\`\`
            ${oldFiles}
            \`\`\`

            _This issue was automatically created by the cleanup workflow._
            `,
              labels: ['maintenance', 'cleanup', 'automated']
            });

  # --- security-audit & database-health-check ジョブは元のまま ---
  # （tar を使っていないので変更不要。全文は割愛）
