name: Deploy TMCloud

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'

jobs:
# ─────────────────────────── Staging ───────────────────────────
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create test database
        run: python scripts/create_test_database.py

      - name: Smoke tests
        run: |
          python - <<'PY'
          import sqlite3, subprocess, os, signal, time, urllib.request
          conn = sqlite3.connect('test_data/test_ci.db')
          assert conn.execute('SELECT COUNT(*) FROM jiken_c_t').fetchone()[0] > 0
          conn.close()
          p = subprocess.Popen(['python','app_dynamic_join_claude_optimized.py'])
          time.sleep(10)
          urllib.request.urlopen('http://localhost:5002/')
          os.kill(p.pid, signal.SIGTERM)
          PY

      - name: Package staging artifact
        run: git archive --format=tar.gz --output=tmcloud-staging.tar.gz HEAD

      - name: Upload staging artifact
        uses: actions/upload-artifact@v4
        with:
          name: tmcloud-staging
          path: tmcloud-staging.tar.gz
          retention-days: 30

# ───────────────────────── Production ─────────────────────────
  deploy-production:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cyclonedx-bom

      - name: Run full test suite
        run: |
          python scripts/create_test_database.py
          python comprehensive_search_test.py

      - name: Generate SBOM
        run: cyclonedx-py -r requirements.txt -o sbom.json

      - name: Package production artifact (+SBOM)
        run: |
          git archive --format=tar --output=tmcloud-production.tar HEAD
          tar --append --file=tmcloud-production.tar sbom.json
          gzip -f tmcloud-production.tar               # → tmcloud-production.tar.gz

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:      ${{ github.ref }}
          release_name:  TMCloud ${{ github.ref }}
          body:          See changelog for details.
          draft:         false
          prerelease:    false

      - name: Upload production artifact
        uses: actions/upload-artifact@v4
        with:
          name: tmcloud-production
          path: tmcloud-production.tar.gz
          retention-days: 90
